### ISSUE TITLE
Feature request: upload the patch as an artifact

### ISSUE THREAD

**Issue by iphydf** [restyled-io/actions#46]
This would make it a bit easier to write tools that can download and apply the patch instead of having to download the logs and grepping out the base64 stuff (or the diff before that).

https://github.com/actions/upload-artifact

**Comment by pbrisbin** [comment]
I thought about this and decided it was not actually that much easier. It's not possible to upload and view a _plain text_ artifact (wouldn't that be nice!). So, even if we stored one, users would still need to download it as a zip, unzip it, then apply it. And even that can't be fully automated as a tool since downloading is a user action in a browser... it all felt a bit clunky. Am I missing something about how that flow could be better automated?

That said, this would be something anyone can accomplish themselves:

```yaml
- run: |
    cat > /restyled.patch <<'EOM'
    ${{ steps.restyler.outputs.patch }}
    EOM
- uses: actions/upload-artifact@v4
  with:
    path: /tmp/restyled.patch
```

I just didn't document it in the example workflows because of the ergonomics issues I mentioned.

> instead of having to download the logs and grepping out the base64 stuff

I imagined users would copy/paste, rather than download and grep. Does that not work?
